// Commandes supplémentaires (texte seul : l'image d'exemple n'existe que pour une commande par catégorie).
// kind : ce que la commande transforme (product, dish, person, place). Il sert à ajouter la consigne « plusieurs éléments / adapter au contexte ».
export const KIND = {
  fashionposter: 'product', lookbook: 'person', productglow: 'product', splashshot: 'product', menuhero: 'dish', bakerymorning: 'dish',
  openhouse: 'place', roomstaging: 'place', matchday: 'person', workoutbanner: 'person', coverdrop: 'person', gigflyer: 'person',
  reelcover: 'person', thumbpunch: 'person', eventnight: 'person', weddinginvite: 'person', skincareglow: 'product', hairshowcase: 'person',
};

// [slug, catégorie, format, kind, glow-x, glow-y, forme, FR{titre, affiche, description, commande}, EN{…}]
const R = [
  ['flatlay', 'mode', '4:5', 'product', '60%', '70%', '8%',
    ['Vêtements à plat', 'Tenue du jour', 'Une tenue et ses accessoires posés à plat, vue du dessus, pour une affiche mode propre.',
      'Avec les vêtements et accessoires de la photo jointe, crée une composition à plat vue du dessus, format vertical 4:5 : pièces bien alignées et espacées, fond uni clair, lumière douce sans ombre dure. Chaque pièce reste identique (coupe, couleurs, motifs).'],
    ['Flat lay outfit', 'Outfit of the day', 'An outfit and its accessories laid flat, seen from above, for a clean fashion poster.',
      'With the clothes and accessories in the attached photo, create a top-down flat-lay composition, vertical 4:5: pieces neatly aligned and spaced, plain light background, soft light without harsh shadows. Each piece stays identical (cut, colors, patterns).']],
  ['streetfit', 'mode', '4:5', 'person', '40%', '70%', '50%',
    ['Mode urbaine', 'Street style', 'Une tenue portée en pleine ville, ambiance streetwear, fond de rue flou.',
      'À partir de la photo jointe, crée une affiche streetwear verticale 4:5 : la personne et la tenue restent identiques, décor urbain flou (mur, rue, graffitis discrets), lumière dorée de fin de journée, cadrage de mode. Grand espace libre en haut. Aucun texte ni logo ajouté.'],
    ['Street style', 'Street style', 'An outfit worn in the city, streetwear mood, blurred street background.',
      'From the attached photo, create a vertical 4:5 streetwear poster: the person and outfit stay identical, blurred urban setting (wall, street, discreet graffiti), golden late-day light, fashion framing. Large free space at the top. No added text or logo.']],
  ['saleposter', 'mode', '4:5', 'product', '70%', '30%', '50%',
    ['Affiche de soldes', 'Soldes', 'Un visuel de promotion qui met le vêtement en avant, avec de la place pour le pourcentage.',
      'Transforme la photo jointe en affiche de promotion de mode, format vertical 4:5 : le ou les vêtements restent identiques, fond de couleur vive unie, énergie et dynamisme, grande zone libre à gauche ou en haut pour afficher un pourcentage de réduction. Aucun texte ni chiffre ajouté.'],
    ['Sale poster', 'Sale', 'A promotion visual that puts the garment first, with room for the percentage.',
      'Turn the attached photo into a fashion promotion poster, vertical 4:5: the garment(s) stay identical, plain vivid-color background, energy and dynamism, large free area on the left or top to show a discount percentage. No added text or numbers.']],

  ['packshot', 'produit', '1:1', 'product', '50%', '50%', '8%',
    ['Photo produit sur fond blanc', 'Packshot', 'La photo propre de boutique en ligne : fond blanc, ombre naturelle, produit net.',
      'Transforme la photo jointe en photo produit de boutique en ligne : fond blanc pur, lumière de studio douce et uniforme, légère ombre naturelle sous le produit, cadrage centré, format carré 1:1. Garde le produit parfaitement identique (forme, couleurs, logo, étiquette). Aucun texte ajouté.'],
    ['White-background product shot', 'Packshot', 'The clean online-store photo: white background, natural shadow, sharp product.',
      'Turn the attached photo into an online-store product shot: pure white background, soft even studio light, a light natural shadow under the product, centered framing, square 1:1 format. Keep the product perfectly identical (shape, colors, logo, label). No added text.']],
  ['lifestyle', 'produit', '4:5', 'product', '35%', '65%', '50%',
    ['Produit en situation', 'Au quotidien', 'Le produit mis en scène dans son vrai usage, pour que le client se projette.',
      'Place le ou les produits de la photo jointe dans une scène de vie réaliste qui correspond à leur usage réel, lumière naturelle, décor simple et crédible, format vertical 4:5, léger flou d’arrière-plan. Le produit reste identique et bien visible au premier plan. Aucun texte ajouté.'],
    ['Product in use', 'Everyday', 'The product staged in its real use, so the customer can picture it.',
      'Place the product(s) from the attached photo in a realistic life scene matching their real use, natural light, simple believable setting, vertical 4:5 format, light background blur. The product stays identical and clearly visible in the foreground. No added text.']],
  ['rangeset', 'produit', '4:5', 'product', '50%', '60%', '50%',
    ['Gamme de produits', 'Toute la gamme', 'Plusieurs produits réunis dans une composition équilibrée, pour présenter une gamme.',
      'Avec tous les produits de la photo jointe, crée une composition publicitaire équilibrée, format vertical 4:5 : produits alignés ou groupés par hauteurs différentes, tous visibles, identiques à la photo, fond de couleur douce harmonisé à leurs couleurs, lumière de studio, léger reflet au sol. Grand espace libre en haut. Aucun texte ajouté.'],
    ['Product range', 'The full range', 'Several products brought together in a balanced composition to present a range.',
      'With all the products in the attached photo, create a balanced advertising composition, vertical 4:5: products lined up or grouped at different heights, all visible, identical to the photo, soft background color matching theirs, studio light, a light reflection on the floor. Large free space at the top. No added text.']],

  ['streetfood', 'food', '4:5', 'dish', '55%', '65%', '50%',
    ['Plat de rue', 'Street food', 'Un plat de rue appétissant, ambiance de soirée, lumière chaude et fumée légère.',
      'Le plat de la photo jointe en plan rapproché, ambiance street food de soirée : lumière chaude, légère fumée, fond urbain flou aux lumières douces, format vertical 4:5. Le plat reste fidèle à la photo, sans ajouter d’ingrédient ni de texte.'],
    ['Street food dish', 'Street food', 'An appetizing street dish, evening mood, warm light and light smoke.',
      'The dish in the attached photo in close-up, evening street-food mood: warm light, light smoke, blurred urban background with soft lights, vertical 4:5 format. The dish stays faithful to the photo, no added ingredient or text.']],
  ['brunchtable', 'food', '1:1', 'dish', '50%', '50%', '50%',
    ['Table vue du dessus', 'Brunch', 'Plusieurs plats sur une table, vue du dessus, pour une carte ou un brunch.',
      'Avec les plats et boissons de la photo jointe, crée une photo vue du dessus, format carré 1:1 : tous les éléments restent identiques et bien visibles, table en bois clair ou nappe simple, lumière naturelle douce, composition équilibrée. Aucun texte ajouté.'],
    ['Table from above', 'Brunch', 'Several dishes on a table, seen from above, for a menu or a brunch.',
      'With the dishes and drinks in the attached photo, create a top-down photo, square 1:1: all items stay identical and clearly visible, light wooden table or a simple tablecloth, soft natural light, balanced composition. No added text.']],
  ['drinkpour', 'food', '4:5', 'dish', '40%', '30%', '50%',
    ['Boisson bien fraîche', 'Bien frais', 'Une boisson avec condensation et glaçons, qui donne soif.',
      'La ou les boissons de la photo jointe avec de la condensation sur le verre ou la bouteille, glaçons et gouttes nettes, fond dégradé coloré en accord avec la boisson, format vertical 4:5. La boisson reste identique (couleur, contenant, étiquette). Aucun texte ajouté.'],
    ['Ice-cold drink', 'Ice cold', 'A drink with condensation and ice cubes that makes you thirsty.',
      'The drink(s) in the attached photo with condensation on the glass or bottle, ice cubes and crisp droplets, colorful gradient background matching the drink, vertical 4:5 format. The drink stays identical (color, container, label). No added text.']],

  ['interiorwarm', 'immobilier', '3:2', 'place', '60%', '55%', '8%',
    ['Intérieur chaleureux', 'Comme chez soi', 'Une pièce de vie mise en valeur par une lumière dorée accueillante.',
      'À partir de la photo jointe d’une pièce, ajoute une lumière chaude et dorée (fin de journée, lampes allumées), avec un rendu photo réaliste, format paysage 3:2. Ne modifie ni la structure, ni les murs, ni les fenêtres, ni les meubles existants. Aucun texte ajouté.'],
    ['Warm interior', 'Feels like home', 'A living space brought out by an inviting golden light.',
      'From the attached photo of a room, add warm golden light (late-day, lamps on), with a realistic photo look, landscape 3:2 format. Do not change the structure, walls, windows or existing furniture. No added text.']],
  ['dronehome', 'immobilier', '3:2', 'place', '50%', '40%', '8%',
    ['Vue aérienne du bien', 'Vue du ciel', 'Le bien présenté de haut, avec son terrain et son environnement.',
      'Imagine une vue aérienne en légère plongée du bien de la photo jointe, format paysage 3:2 : architecture, toiture et terrain identiques, environnement cohérent (jardin, rue, arbres), lumière douce de milieu de matinée, rendu photo réaliste. Aucun texte ajouté.'],
    ['Aerial view of the property', 'From above', 'The property shown from above, with its plot and surroundings.',
      'Imagine a slightly tilted aerial view of the property in the attached photo, landscape 3:2: architecture, roof and plot identical, consistent surroundings (garden, street, trees), soft mid-morning light, realistic photo look. No added text.']],
  ['forrent', 'immobilier', '4:5', 'place', '35%', '30%', '8%',
    ['Affiche à louer', 'À louer', 'Une affiche sobre pour un appartement ou une maison à louer.',
      'Transforme la photo jointe du bien en affiche immobilière sobre, format vertical 4:5 : la photo occupe le haut, bandeau uni lisible en bas avec de la place pour le loyer, la surface et le contact. Architecture identique, lumière claire. Aucun texte ni chiffre ajouté.'],
    ['For rent poster', 'For rent', 'A clean poster for an apartment or house for rent.',
      'Turn the attached photo of the property into a clean real-estate poster, vertical 4:5: the photo fills the top, a plain readable band at the bottom with room for the rent, the surface and the contact. Architecture identical, bright light. No added text or numbers.']],

  ['tournament', 'sport', '4:5', 'person', '50%', '30%', '50%',
    ['Affiche de tournoi', 'Tournoi', 'Une affiche de tournoi dynamique, avec de la place pour le programme.',
      'Avec la photo jointe des joueurs ou du ballon, crée une affiche de tournoi verticale 4:5 : lumière de stade, énergie, couleurs d’équipe conservées, personnes identiques, fond sombre texturé. Grande zone libre en haut pour le nom du tournoi et en bas pour les dates. Aucun texte ajouté.'],
    ['Tournament poster', 'Tournament', 'A dynamic tournament poster with room for the schedule.',
      'With the attached photo of the players or the ball, create a vertical 4:5 tournament poster: stadium light, energy, team colors kept, people identical, dark textured background. Large free area at the top for the tournament name and at the bottom for the dates. No added text.']],
  ['runnerdawn', 'sport', '9:16', 'person', '50%', '75%', '50%',
    ['Course à l’aube', 'Cours', 'Un coureur au lever du jour, pour motiver une communauté de sport.',
      'À partir de la photo jointe, crée un visuel vertical 9:16 : la personne qui court reste identique, lever de soleil, brume légère, lumière rasante dorée, route ou piste, sensation de mouvement. Espace libre en haut pour un titre. Aucun texte ajouté.'],
    ['Dawn run', 'Run', 'A runner at daybreak, to motivate a sports community.',
      'From the attached photo, create a vertical 9:16 visual: the running person stays identical, sunrise, light haze, golden low light, road or track, a feeling of movement. Free space at the top for a title. No added text.']],
  ['teamlineup', 'sport', '3:2', 'person', '50%', '50%', '50%',
    ['Équipe alignée', 'Notre équipe', 'La photo d’équipe transformée en affiche de saison.',
      'Avec la photo jointe de l’équipe, crée une affiche de saison au format paysage 3:2 : tous les joueurs restent identiques et bien visibles, couleurs du maillot conservées, ciel dramatique ou stade en arrière-plan, contraste fort. Grande zone libre en haut. Aucun texte ajouté.'],
    ['Team lineup', 'Our team', 'The team photo turned into a season poster.',
      'With the attached team photo, create a season poster in landscape 3:2: all players stay identical and clearly visible, jersey colors kept, dramatic sky or stadium in the background, strong contrast. Large free area at the top. No added text.']],

  ['djnight', 'musique', '4:5', 'person', '50%', '30%', '50%',
    ['Soirée DJ', 'DJ set', 'Une affiche de DJ set avec lumières de club et silhouette bien détachée.',
      'Avec la photo jointe du DJ, crée une affiche de soirée verticale 4:5 : lumières de club colorées, laser et fumée légère, platines visibles, la personne identique. Fond sombre, une couleur d’accent. Espace libre pour le nom et la date. Aucun texte ajouté.'],
    ['DJ night', 'DJ set', 'A DJ set poster with club lights and a well-separated silhouette.',
      'With the attached photo of the DJ, create a vertical 4:5 party poster: colorful club lights, lasers and light haze, decks visible, the person identical. Dark background, one accent color. Free space for the name and the date. No added text.']],
  ['livesession', 'musique', '4:5', 'person', '40%', '60%', '50%',
    ['Session live acoustique', 'Live session', 'Un visuel chaleureux pour une session acoustique ou un concert intimiste.',
      'À partir de la photo jointe, crée un visuel vertical 4:5 pour une session live acoustique : ambiance intimiste, lumière chaude de lampes, grain de film léger, la personne et son instrument identiques. Espace libre pour le titre. Aucun texte ajouté.'],
    ['Acoustic live session', 'Live session', 'A warm visual for an acoustic session or an intimate gig.',
      'From the attached photo, create a vertical 4:5 visual for an acoustic live session: intimate mood, warm lamp light, light film grain, the person and their instrument identical. Free space for the title. No added text.']],
  ['clipteaser', 'musique', '16:9', 'person', '50%', '50%', '50%',
    ['Annonce de clip', 'Nouveau clip', 'Une image cinéma 16:9 pour annoncer la sortie d’un clip.',
      'Avec la photo jointe, crée une image cinématographique 16:9 pour annoncer un clip : cadrage large, contraste cinéma, teinte dominante unique, la personne identique, léger grain. Grande zone libre pour le titre. Aucun texte ajouté.'],
    ['Video release teaser', 'New video', 'A 16:9 cinematic image to announce a music video.',
      'With the attached photo, create a 16:9 cinematic image to announce a music video: wide framing, cinema contrast, one dominant tint, the person identical, light grain. Large free area for the title. No added text.']],

  ['quotecard', 'reseaux', '1:1', 'person', '50%', '50%', '8%',
    ['Visuel citation', 'Citation', 'Un fond élégant pour poser une citation ou une phrase forte.',
      'Crée à partir de la photo jointe un visuel carré 1:1 pour une citation : photo en arrière-plan assombri et légèrement flou, grande zone centrale calme et lisible pour le texte, bords propres. Les personnes ou objets restent identiques. Aucun texte ajouté.'],
    ['Quote card', 'Quote', 'An elegant background to set a quote or a strong sentence on.',
      'From the attached photo, create a square 1:1 visual for a quote: photo as a darkened, slightly blurred background, a large calm readable central area for the text, clean edges. People or objects stay identical. No added text.']],
  ['storyannounce', 'reseaux', '9:16', 'person', '50%', '70%', '50%',
    ['Story d’annonce', 'Nouveauté', 'Une story verticale pour annoncer une nouveauté, avec zones sûres.',
      'Avec la photo jointe, crée une story verticale 9:16 pour annoncer une nouveauté : sujet net et centré, fond simple coloré, zones sûres (rien d’important dans les 15 % du haut et du bas), grand espace libre au centre-bas. Sujet identique. Aucun texte ajouté.'],
    ['Announcement story', 'New', 'A vertical story to announce something new, with safe zones.',
      'With the attached photo, create a vertical 9:16 story to announce something new: sharp centered subject, simple colored background, safe zones (nothing important in the top and bottom 15%), large free space center-bottom. Subject identical. No added text.']],
  ['carouselcover', 'reseaux', '4:5', 'product', '50%', '50%', '8%',
    ['Couverture de carrousel', 'Carrousel', 'La première image d’un carrousel qui donne envie de swiper.',
      'Avec la photo jointe, crée la couverture d’un carrousel au format vertical 4:5 : sujet bien visible, fond simple d’une seule couleur, composition aérée avec une grande zone libre pour un titre accrocheur, petite zone libre en bas à droite pour une flèche. Sujet identique. Aucun texte ajouté.'],
    ['Carousel cover', 'Carousel', 'The first image of a carousel that makes people want to swipe.',
      'With the attached photo, create a carousel cover in vertical 4:5: clearly visible subject, simple single-color background, airy composition with a large free area for a catchy title, a small free area bottom right for an arrow. Subject identical. No added text.']],

  ['inauguration', 'evenement', '4:5', 'person', '50%', '40%', '8%',
    ['Inauguration', 'Inauguration', 'Une affiche d’ouverture sobre et festive pour une boutique ou un restaurant.',
      'À partir de la photo jointe du lieu ou de l’équipe, crée une affiche d’inauguration verticale 4:5 : ambiance festive et élégante, rubans, lumière chaleureuse, lieu et personnes identiques. Grande zone libre pour le nom, la date et l’adresse. Aucun texte ajouté.'],
    ['Grand opening', 'Opening', 'A clean, festive opening poster for a shop or a restaurant.',
      'From the attached photo of the place or the team, create a vertical 4:5 grand-opening poster: festive, elegant mood, ribbons, warm light, place and people identical. Large free area for the name, the date and the address. No added text.']],
  ['conference', 'evenement', '4:5', 'person', '50%', '30%', '8%',
    ['Affiche de conférence', 'Conférence', 'Une affiche professionnelle pour une conférence, une formation ou un webinaire.',
      'Avec la photo jointe de l’intervenant, crée une affiche professionnelle verticale 4:5 : portrait net, fond sobre dégradé bleu nuit, lumière de studio, mise en page aérée avec de la place pour le thème, la date et le lieu. La personne reste identique. Aucun texte ajouté.'],
    ['Conference poster', 'Conference', 'A professional poster for a conference, a training or a webinar.',
      'With the attached photo of the speaker, create a professional vertical 4:5 poster: sharp portrait, understated midnight-blue gradient background, studio light, airy layout with room for the topic, the date and the venue. The person stays identical. No added text.']],
  ['birthdayparty', 'evenement', '4:5', 'person', '50%', '60%', '50%',
    ['Faire-part d’anniversaire', 'Anniversaire', 'Une invitation colorée et joyeuse pour fêter un anniversaire.',
      'Avec la photo jointe de la personne, crée une invitation d’anniversaire verticale 4:5 : couleurs joyeuses, confettis et ballons discrets, la personne identique au centre, fond doux. Grande zone libre pour le prénom, la date et le lieu. Aucun texte ajouté.'],
    ['Birthday invitation', 'Birthday', 'A colorful, joyful invitation to celebrate a birthday.',
      'With the attached photo of the person, create a vertical 4:5 birthday invitation: joyful colors, discreet confetti and balloons, the person identical in the center, soft background. Large free area for the name, the date and the venue. No added text.']],

  ['makeuplook', 'beaute', '4:5', 'person', '40%', '40%', '50%',
    ['Look maquillage', 'Look du jour', 'Un portrait éclairé en studio pour mettre un maquillage en valeur.',
      'À partir de la photo jointe, crée un portrait beauté vertical 4:5 : lumière douce de studio, teint et maquillage bien visibles, fond uni pastel, rendu net. Le visage et le maquillage restent identiques, sans retouche excessive. Espace libre en haut. Aucun texte ajouté.'],
    ['Makeup look', 'Look of the day', 'A studio-lit portrait to showcase a makeup look.',
      'From the attached photo, create a vertical 4:5 beauty portrait: soft studio light, skin and makeup clearly visible, plain pastel background, sharp rendering. The face and makeup stay identical, no excessive retouching. Free space at the top. No added text.']],
  ['nailart', 'beaute', '1:1', 'product', '50%', '50%', '50%',
    ['Ongles en vedette', 'Nail art', 'Des ongles photographiés comme un bijou, sur fond clair brillant.',
      'À partir de la photo jointe des ongles, crée une photo carrée 1:1 : mains posées sur une surface claire brillante, lumière douce, reflets propres, mise au point nette sur les ongles. La forme, la couleur et les motifs restent identiques. Aucun texte ajouté.'],
    ['Nails in the spotlight', 'Nail art', 'Nails photographed like jewelry, on a bright glossy background.',
      'From the attached photo of the nails, create a square 1:1 photo: hands resting on a bright glossy surface, soft light, clean reflections, sharp focus on the nails. Shape, color and patterns stay identical. No added text.']],
  ['barbershop', 'beaute', '4:5', 'person', '50%', '50%', '50%',
    ['Barbier : coupe nette', 'Coupe nette', 'Une coupe ou une barbe mise en valeur avec un éclairage de salon.',
      'Avec la photo jointe, crée une affiche de barbier verticale 4:5 : éclairage de studio contrasté, détails de la coupe et de la barbe bien nets, fond sombre texturé, ambiance classique. La personne reste identique. Espace libre pour le nom du salon. Aucun texte ajouté.'],
    ['Barbershop: clean cut', 'Clean cut', 'A cut or a beard highlighted with salon lighting.',
      'With the attached photo, create a vertical 4:5 barbershop poster: contrasted studio lighting, cut and beard details sharp, dark textured background, classic mood. The person stays identical. Free space for the salon name. No added text.']],
];

export const EXTRA = R.map(([slug, cat, ratio, kind, x, y, r, fr, en]) => ({
  slug, code: '/' + slug, cat, ratio, x, y, r, kind, noImage: true,
  fr: { title: fr[0], poster: fr[1], desc: fr[2], prompt: fr[3] },
  en: { title: en[0], poster: en[1], desc: en[2], prompt: en[3] },
}));
