// Données du site : catégories et commandes. Les commandes sont écrites par nous (aucune marque, aucune personnalité).
// `tested` reste vide tant qu'un résultat réel n'a pas été vérifié : le site n'affiche « testé sur » que pour ce qui l'est vraiment.

export const CATEGORIES = [
  { id: 'mode', fr: 'Mode', en: 'Fashion', fr_d: 'Affiches de collection, lookbooks, promotions : votre vêtement devient une affiche.', en_d: 'Collection posters, lookbooks, promotions: your garment becomes a poster.' },
  { id: 'produit', fr: 'Pub produit', en: 'Product ads', fr_d: 'Un produit, une photo, une affiche publicitaire qui donne envie.', en_d: 'One product, one photo, an advertising poster people want to click.' },
  { id: 'food', fr: 'Food', en: 'Food', fr_d: 'Plats qui donnent faim, menus du jour, promotions de restaurant.', en_d: 'Dishes that make people hungry, daily menus, restaurant promotions.' },
  { id: 'immobilier', fr: 'Immobilier', en: 'Real estate', fr_d: 'Biens à vendre ou à louer, présentés comme dans un magazine.', en_d: 'Properties for sale or rent, presented like in a magazine.' },
  { id: 'sport', fr: 'Sport', en: 'Sport', fr_d: 'Affiches de match, de tournoi, de séance : de l’énergie dès le premier regard.', en_d: 'Match, tournament and workout posters: energy at first glance.' },
  { id: 'musique', fr: 'Musique', en: 'Music', fr_d: 'Pochettes, sorties, concerts : des visuels qui sonnent juste.', en_d: 'Covers, releases, concerts: visuals that sound right.' },
  { id: 'reseaux', fr: 'Réseaux sociaux', en: 'Social media', fr_d: 'Couvertures de Reels, miniatures, annonces : plus vite, plus beau.', en_d: 'Reel covers, thumbnails, announcements: faster and better.' },
  { id: 'evenement', fr: 'Événements', en: 'Events', fr_d: 'Soirées, mariages, inaugurations : l’affiche qui remplit la salle.', en_d: 'Parties, weddings, openings: the poster that fills the room.' },
  { id: 'beaute', fr: 'Beauté', en: 'Beauty', fr_d: 'Soins, coiffure, maquillage : un rendu propre et lumineux.', en_d: 'Skincare, hair, makeup: a clean, luminous look.' },
];

// x, y : position de la lueur sur l'affiche ; r : forme (rayon) ; ratio : format conseillé
import { KIND, EXTRA } from './data_extra.mjs';

const BASE = [
  { slug: 'fashionposter', code: '/fashionposter', cat: 'mode', ratio: '4:5', x: '70%', y: '78%', r: '50%',
    fr: { title: 'Affiche de collection', poster: 'Nouvelle collection', desc: 'Transforme la photo d’un vêtement en affiche de collection, avec de la place pour le titre.',
      prompt: 'Transforme la photo jointe en affiche publicitaire de mode, format vertical 4:5. Le vêtement reste identique (coupe, couleurs, motifs). Fond uni sobre, lumière de studio douce, ombre légère sous le vêtement. Grand espace libre en haut pour le titre. Rendu net, éditorial, sans texte inventé.' },
    en: { title: 'Collection poster', poster: 'New collection', desc: 'Turns a garment photo into a collection poster, with room for the headline.',
      prompt: 'Turn the attached photo into a fashion advertising poster, vertical 4:5. The garment stays identical (cut, colors, patterns). Plain, understated background, soft studio light, light shadow under the garment. Large empty space at the top for the headline. Sharp, editorial look, no invented text.' } },
  { slug: 'lookbook', code: '/lookbook', cat: 'mode', ratio: '3:4', x: '30%', y: '70%', r: '8%',
    fr: { title: 'Page de lookbook', poster: 'Look de saison', desc: 'Présente une tenue comme une page de lookbook, sobre et haut de gamme.',
      prompt: 'À partir de la photo jointe, crée une page de lookbook de mode, format 3:4. La tenue reste identique. Fond neutre texturé (papier ou béton clair), cadrage éditorial, grandes marges, lumière naturelle douce. Style magazine minimaliste, sans logo ni texte ajouté.' },
    en: { title: 'Lookbook page', poster: 'Season look', desc: 'Presents an outfit like a lookbook page, understated and upscale.',
      prompt: 'From the attached photo, create a fashion lookbook page, 3:4 format. The outfit stays identical. Neutral textured background (paper or light concrete), editorial framing, generous margins, soft natural light. Minimalist magazine style, no logo or added text.' } },
  { slug: 'productglow', code: '/productglow', cat: 'produit', ratio: '4:5', x: '30%', y: '70%', r: '50%',
    fr: { title: 'Produit en lévitation', poster: 'Édition limitée', desc: 'Le produit flotte dans un halo lumineux sur fond sombre : l’effet “premium” immédiat.',
      prompt: 'Le produit de la photo jointe lévite au centre dans un halo lumineux, fond sombre dégradé, ombre douce, lumière de studio. Affiche publicitaire verticale 4:5, espace libre en haut pour le titre. Garde le produit parfaitement identique (forme, couleurs, logo, étiquette).' },
    en: { title: 'Floating product', poster: 'Limited edition', desc: 'The product floats in a glowing halo on a dark background: instant “premium” feel.',
      prompt: 'The product in the attached photo floats in the center in a glowing halo, dark gradient background, soft shadow, studio light. Vertical 4:5 advertising poster, free space at the top for the headline. Keep the product perfectly identical (shape, colors, logo, label).' } },
  { slug: 'splashshot', code: '/splashshot', cat: 'produit', ratio: '1:1', x: '65%', y: '35%', r: '50%',
    fr: { title: 'Produit et éclaboussures', poster: 'Fraîcheur', desc: 'Le produit au milieu d’éclaboussures figées : idéal pour boissons, cosmétiques, soins.',
      prompt: 'Le produit de la photo jointe au centre, entouré d’éclaboussures figées en plein mouvement, adaptées à l’univers du produit (de l’eau pour une boisson, de la crème ou des pétales pour un cosmétique, etc.), gouttes nettes, reflets frais, fond dégradé aux couleurs du produit. Format carré 1:1, lumière de studio. Le produit reste identique (forme, couleurs, logo).' },
    en: { title: 'Product with splashes', poster: 'Fresh', desc: 'The product amid frozen splashes: ideal for drinks, cosmetics, skincare.',
      prompt: 'The product from the attached photo in the center, surrounded by splashes frozen mid-motion, matched to the product’s world (water for a drink, cream or petals for a cosmetic, etc.), crisp droplets, fresh reflections, gradient background in the product’s colors. Square 1:1 format, studio light. The product stays identical (shape, colors, logo).' } },
  { slug: 'menuhero', code: '/menuhero', cat: 'food', ratio: '4:5', x: '60%', y: '60%', r: '50%',
    fr: { title: 'Plat vedette du menu', poster: 'Menu du jour', desc: 'Un plat en gros plan, vapeur et lumière chaude, pour une affiche de menu qui donne faim.',
      prompt: 'Le plat de la photo jointe en gros plan, légère vapeur, lumière chaude latérale, fond sombre flou, ingrédients frais autour. Affiche de restaurant verticale 4:5 avec espace libre en bas pour le prix. Le plat reste fidèle à la photo, sans ajouter d’ingrédients ni de texte.' },
    en: { title: 'Menu hero dish', poster: 'Dish of the day', desc: 'A close-up dish with steam and warm light, for a menu poster that makes people hungry.',
      prompt: 'The dish in the attached photo in close-up, light steam, warm side light, dark blurred background, fresh ingredients around. Vertical 4:5 restaurant poster with free space at the bottom for the price. The dish stays faithful to the photo, no added ingredients or text.' } },
  { slug: 'bakerymorning', code: '/bakerymorning', cat: 'food', ratio: '1:1', x: '35%', y: '30%', r: '24%',
    fr: { title: 'Matin de boulangerie', poster: 'Frais du matin', desc: 'Pains et pâtisseries en lumière du matin, pour une promo de boulangerie ou de café.',
      prompt: 'Les produits de la photo jointe posés sur une table en bois clair, lumière du matin à travers une fenêtre, légère farine en suspension, ambiance chaleureuse. Format carré 1:1, espace libre pour une offre. Les produits restent identiques.' },
    en: { title: 'Bakery morning', poster: 'Fresh this morning', desc: 'Breads and pastries in morning light, for a bakery or café promotion.',
      prompt: 'The products from the attached photo on a light wooden table, morning light through a window, a little flour in the air, warm atmosphere. Square 1:1 format, free space for an offer. The products stay identical.' } },
  { slug: 'openhouse', code: '/openhouse', cat: 'immobilier', ratio: '4:5', x: '25%', y: '80%', r: '8%',
    fr: { title: 'Maison à vendre, style magazine', poster: 'Visite ce samedi', desc: 'Un bien immobilier au crépuscule, façon couverture de magazine d’architecture.',
      prompt: 'La façade de la photo jointe au crépuscule, fenêtres allumées, ciel dégradé, jardin soigné, rendu type magazine d’architecture. Affiche verticale 4:5 avec espace libre en haut pour le titre et en bas pour les coordonnées. L’architecture reste identique.' },
    en: { title: 'Magazine open house', poster: 'Open this Saturday', desc: 'A property at dusk, like an architecture magazine cover.',
      prompt: 'The facade in the attached photo at dusk, lit windows, gradient sky, tidy garden, architecture-magazine look. Vertical 4:5 poster with free space at the top for the headline and at the bottom for contact details. The architecture stays identical.' } },
  { slug: 'roomstaging', code: '/roomstaging', cat: 'immobilier', ratio: '3:2', x: '70%', y: '55%', r: '12%',
    fr: { title: 'Pièce mise en scène', poster: 'Appartement lumineux', desc: 'Une pièce vide meublée et décorée avec goût, pour mieux vendre ou louer.',
      prompt: 'Avec la photo jointe d’une pièce, ajoute un mobilier moderne sobre et une décoration chaleureuse (canapé, table basse, plantes, tapis), lumière naturelle. Ne change ni les murs, ni les fenêtres, ni les dimensions. Rendu photo réaliste, format paysage 3:2.' },
    en: { title: 'Staged room', poster: 'Bright apartment', desc: 'An empty room furnished and styled with taste, to sell or rent better.',
      prompt: 'With the attached photo of a room, add understated modern furniture and warm decor (sofa, coffee table, plants, rug), natural light. Do not change the walls, windows or dimensions. Realistic photo look, landscape 3:2 format.' } },
  { slug: 'matchday', code: '/matchday', cat: 'sport', ratio: '4:5', x: '75%', y: '65%', r: '50%',
    fr: { title: 'Affiche de match', poster: 'Match day', desc: 'Une affiche d’énergie pour un match, un tournoi ou une rencontre de club.',
      prompt: 'Avec la photo jointe du sportif ou de l’équipe, crée une affiche de match verticale 4:5 : contraste fort, lumière de stade, particules d’énergie, fond sombre. Garde le visage et la tenue identiques. Grand espace libre pour la date et les équipes.' },
    en: { title: 'Match day poster', poster: 'Match day', desc: 'A high-energy poster for a match, tournament or club game.',
      prompt: 'With the attached photo of the athlete or team, create a vertical 4:5 match poster: strong contrast, stadium light, energy particles, dark background. Keep the face and outfit identical. Large free space for the date and teams.' } },
  { slug: 'workoutbanner', code: '/workoutbanner', cat: 'sport', ratio: '9:16', x: '40%', y: '75%', r: '50%',
    fr: { title: 'Bannière de séance', poster: 'Séance du jour', desc: 'Un visuel de story pour annoncer un cours collectif ou une séance de coaching.',
      prompt: 'À partir de la photo jointe, crée un visuel vertical 9:16 pour annoncer une séance de sport : mouvement dynamique, éclairage contrasté, fond sombre texturé, touche de couleur vive. Le visage reste identique. Espace libre en haut pour l’horaire. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Workout banner', poster: 'Today’s session', desc: 'A story visual to announce a group class or a coaching session.',
      prompt: 'From the attached photo, create a vertical 9:16 visual announcing a workout session: dynamic movement, contrasted lighting, dark textured background, a touch of bright color. The face stays identical. Free space at the top for the time. No added text or prices: leave the free areas empty.' } },
  { slug: 'coverdrop', code: '/coverdrop', cat: 'musique', ratio: '1:1', x: '40%', y: '75%', r: '50%',
    fr: { title: 'Pochette de sortie', poster: 'Nouveau single', desc: 'Une pochette carrée forte pour annoncer un morceau ou un album.',
      prompt: 'Crée une pochette carrée 1:1 à partir de la photo jointe : portrait centré, contraste fort, grain de film léger, une couleur dominante unique, fond épuré. Le visage reste identique. Laisse de la place pour le titre en grosses lettres, sans inventer de texte.' },
    en: { title: 'Release cover', poster: 'New single', desc: 'A strong square cover to announce a track or an album.',
      prompt: 'Create a 1:1 square cover from the attached photo: centered portrait, strong contrast, light film grain, a single dominant color, clean background. The face stays identical. Leave room for the title in large letters, without inventing text.' } },
  { slug: 'gigflyer', code: '/gigflyer', cat: 'musique', ratio: '4:5', x: '65%', y: '30%', r: '50%',
    fr: { title: 'Affiche de concert', poster: 'En concert', desc: 'Lumières de scène et fumée pour annoncer un concert ou une soirée DJ.',
      prompt: 'Avec la photo jointe de l’artiste, crée une affiche de concert verticale 4:5 : faisceaux de lumière de scène, fumée légère, silhouette bien détachée, fond sombre, accent de couleur unique. Le visage reste identique. Espace libre pour le nom, la date et le lieu. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Concert poster', poster: 'Live', desc: 'Stage lights and haze to announce a concert or a DJ night.',
      prompt: 'With the attached photo of the artist, create a vertical 4:5 concert poster: stage light beams, light haze, well-separated silhouette, dark background, a single color accent. The face stays identical. Free space for the name, date and venue. No added text or prices: leave the free areas empty.' } },
  { slug: 'reelcover', code: '/reelcover', cat: 'reseaux', ratio: '9:16', x: '65%', y: '72%', r: '24%',
    fr: { title: 'Couverture de Reel', poster: 'Épisode 12', desc: 'Une couverture verticale lisible, même en petit, pour vos vidéos courtes.',
      prompt: 'Avec la photo jointe, crée une couverture de vidéo courte au format 9:16 : sujet net au centre, fond simplifié très contrasté, grande zone libre au centre-bas pour un titre lisible, bords sûrs (rien d’important en haut et en bas). Le visage reste identique. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Reel cover', poster: 'Episode 12', desc: 'A vertical cover that stays readable even small, for your short videos.',
      prompt: 'With the attached photo, create a short-video cover in 9:16: sharp subject in the center, simplified high-contrast background, large free area center-bottom for a readable title, safe edges (nothing important at the very top and bottom). The face stays identical. No added text or prices: leave the free areas empty.' } },
  { slug: 'thumbpunch', code: '/thumbpunch', cat: 'reseaux', ratio: '16:9', x: '70%', y: '40%', r: '50%',
    fr: { title: 'Miniature qui se remarque', poster: 'Il faut voir ça', desc: 'Une miniature de vidéo avec un sujet détaché et un fond qui accroche l’œil.',
      prompt: 'Transforme la photo jointe en miniature de vidéo 16:9 : sujet détaché avec un fin contour lumineux, expression bien visible, fond coloré simple et saturé, grand espace libre à gauche pour 3 à 4 mots. Le visage reste identique.' },
    en: { title: 'Thumbnail that stands out', poster: 'You have to see this', desc: 'A video thumbnail with a cut-out subject and an eye-catching background.',
      prompt: 'Turn the attached photo into a 16:9 video thumbnail: cut-out subject with a thin glowing outline, clearly visible expression, simple saturated colored background, large free space on the left for 3 to 4 words. The face stays identical.' } },
  { slug: 'eventnight', code: '/eventnight', cat: 'evenement', ratio: '4:5', x: '30%', y: '65%', r: '50%',
    fr: { title: 'Soirée à thème', poster: 'Samedi 22h', desc: 'Ambiance de soirée : lumières, couleurs, énergie, avec la place pour le programme.',
      prompt: 'À partir de la photo jointe, crée une affiche de soirée verticale 4:5 : ambiance de club, lumières colorées douces, brume légère, sujet bien visible. Garde les personnes identiques. Grande zone libre pour la date, le lieu et le programme. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Theme night', poster: 'Saturday 10pm', desc: 'Party atmosphere: lights, colors, energy, with room for the program.',
      prompt: 'From the attached photo, create a vertical 4:5 party poster: club atmosphere, soft colored lights, light haze, subject clearly visible. Keep the people identical. Large free area for the date, venue and program. No added text or prices: leave the free areas empty.' } },
  { slug: 'weddinginvite', code: '/weddinginvite', cat: 'evenement', ratio: '4:5', x: '55%', y: '25%', r: '50%',
    fr: { title: 'Faire-part élégant', poster: 'Save the date', desc: 'Un faire-part ou “save the date” doux et raffiné à partir d’une photo de couple.',
      prompt: 'Avec la photo jointe du couple, crée un faire-part vertical 4:5 : tons doux et chauds, lumière dorée, cadre fin, fond légèrement flou. Garde les visages identiques. Grande zone libre pour les noms et la date, style sobre et élégant. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Elegant invitation', poster: 'Save the date', desc: 'A soft, refined invitation or “save the date” from a couple photo.',
      prompt: 'With the attached photo of the couple, create a vertical 4:5 invitation: soft warm tones, golden light, thin frame, slightly blurred background. Keep the faces identical. Large free area for the names and date, understated elegant style. No added text or prices: leave the free areas empty.' } },
  { slug: 'skincareglow', code: '/skincareglow', cat: 'beaute', ratio: '4:5', x: '60%', y: '45%', r: '50%',
    fr: { title: 'Soin lumineux', poster: 'Peau lumineuse', desc: 'Un produit de soin sur fond clair et brillant, pour une affiche douce et propre.',
      prompt: 'Le produit de soin de la photo jointe posé sur une surface claire brillante, reflets doux, gouttes d’eau fines, fond dégradé pastel. Affiche verticale 4:5, espace libre en haut. Le produit reste identique (forme, couleurs, étiquette).' },
    en: { title: 'Luminous skincare', poster: 'Glowing skin', desc: 'A skincare product on a bright glossy background, for a soft, clean poster.',
      prompt: 'The skincare product in the attached photo on a bright glossy surface, soft reflections, fine water droplets, pastel gradient background. Vertical 4:5 poster, free space at the top. The product stays identical (shape, colors, label).' } },
  { slug: 'hairshowcase', code: '/hairshowcase', cat: 'beaute', ratio: '4:5', x: '35%', y: '60%', r: '50%',
    fr: { title: 'Vitrine coiffure', poster: 'Nouvelle coupe', desc: 'Met en valeur une coiffure ou une couleur avec un éclairage de salon professionnel.',
      prompt: 'Avec la photo jointe, crée une affiche de salon de coiffure verticale 4:5 : éclairage doux de studio, reflets brillants sur les cheveux, fond neutre légèrement dégradé. La coiffure et le visage restent identiques. Espace libre pour le nom du salon et le prix. Aucun texte ni prix ajouté : laisse les zones libres vides.' },
    en: { title: 'Hair showcase', poster: 'New cut', desc: 'Highlights a hairstyle or color with professional salon lighting.',
      prompt: 'With the attached photo, create a vertical 4:5 hair salon poster: soft studio lighting, shiny highlights on the hair, neutral slightly graded background. The hairstyle and face stay identical. Free space for the salon name and price. No added text or prices: leave the free areas empty.' } },
];

export const COMMANDS = [...BASE.map((c) => ({ ...c, kind: KIND[c.slug] })), ...EXTRA];
