# -*- coding: utf-8 -*-
"""Traductions (es, de, ar, pt, zh, sw) et mots-clés du pack Afrolook « Universel ».

Clé = légende française (telle qu'elle figure dans catalog_universel.json).
Valeur = (es, de, ar, pt, zh, sw).
"""

LANGS = ["fr", "en", "es", "de", "ar", "pt", "zh", "sw"]
EXTRA_LANGS = ["es", "de", "ar", "pt", "zh", "sw"]

TR = {
    # --- Joie et rire
    "MDR": ("Jajaja", "Haha", "ههههه", "Kkkk", "哈哈哈", "Hahaha"),
    "Fou rire aux larmes": ("Llorando de risa", "Tränen gelacht", "أبكي من الضحك", "Chorando de rir", "笑出眼泪", "Kicheko cha machozi"),
    "Grand sourire": ("Gran sonrisa", "Breites Lächeln", "ابتسامة كبيرة", "Sorrisão", "大大的微笑", "Tabasamu kubwa"),
    "Youpi": ("¡Yupi!", "Juhu", "يا هلا", "Uhul", "耶", "Hoyee"),
    "Trop drôle": ("Qué gracioso", "So lustig", "مضحك جدا", "Muito engraçado", "太搞笑了", "Inachekesha sana"),
    "Petit sourire": ("Sonrisita", "Kleines Lächeln", "ابتسامة خفيفة", "Sorrisinho", "微微一笑", "Tabasamu dogo"),
    "Ravi": ("Encantado", "Begeistert", "سعيد جدا", "Radiante", "太开心", "Nimefurahi"),
    "Danse de joie": ("Baile de alegría", "Freudentanz", "رقصة الفرح", "Dança da alegria", "开心舞", "Ngoma ya furaha"),
    "Hihi": ("Jiji", "Hihi", "هيهي", "Hihi", "嘻嘻", "Hihi"),
    "Rire gêné": ("Risa nerviosa", "Peinliches Lachen", "ضحكة محرجة", "Riso sem graça", "尴尬地笑", "Kicheko cha aibu"),
    "Ça me fait plaisir": ("Me alegra", "Freut mich", "يسعدني هذا", "Fico feliz", "我很高兴", "Inanifurahisha"),
    "On fait la fête": ("¡A festejar!", "Party-Zeit", "وقت الحفلة", "Hora da festa", "派对时间", "Wakati wa sherehe"),
    # --- Félicitations et réussite
    "Félicitations": ("Felicidades", "Glückwunsch", "مبروك", "Parabéns", "恭喜", "Hongera"),
    "Bravo": ("Bravo", "Bravo", "أحسنت", "Bravo", "干得好", "Vizuri sana"),
    "Champion": ("Campeón", "Champion", "بطل", "Campeão", "冠军", "Bingwa"),
    "Objectif atteint": ("Objetivo logrado", "Ziel erreicht", "تحقق الهدف", "Meta alcançada", "目标达成", "Lengo limefikiwa"),
    "Diplômé": ("Graduado", "Absolvent", "متخرج", "Formado", "毕业啦", "Amehitimu"),
    "Nouveau travail": ("Nuevo trabajo", "Neuer Job", "وظيفة جديدة", "Novo emprego", "新工作", "Kazi mpya"),
    "Promotion": ("Ascenso", "Beförderung", "ترقية", "Promoção", "升职了", "Kupandishwa cheo"),
    "Médaille d'or": ("Medalla de oro", "Goldmedaille", "ميدالية ذهبية", "Medalha de ouro", "金牌", "Medali ya dhahabu"),
    "Standing ovation": ("Ovación de pie", "Standing Ovations", "تصفيق حار", "Aplausos de pé", "起立鼓掌", "Makofi ya kusimama"),
    "Chapeau": ("Chapó", "Hut ab", "أرفع قبعتي", "Tiro o chapéu", "佩服", "Nakupongeza"),
    "Tu as réussi": ("¡Lo lograste!", "Du hast es geschafft", "لقد نجحت", "Você conseguiu", "你做到了", "Umefanikiwa"),
    "Record battu": ("Récord batido", "Neuer Rekord", "رقم قياسي جديد", "Recorde batido", "打破纪录", "Rekodi mpya"),
    "Étoile du jour": ("Estrella del día", "Stern des Tages", "نجم اليوم", "Estrela do dia", "今日之星", "Nyota ya siku"),
    "On célèbre": ("A celebrar", "Wir feiern", "لنحتفل", "Vamos comemorar", "一起庆祝", "Tusherehekee"),
    # --- Compliments
    "Trop beau": ("Qué guapo", "So schön", "جميل جدا", "Lindo demais", "太美了", "Mzuri sana"),
    "Tu brilles": ("Brillas", "Du strahlst", "أنت تتألق", "Você brilha", "你闪闪发光", "Unang'aa"),
    "Quelle classe": ("Qué clase", "So stilvoll", "يا لها من أناقة", "Que classe", "好有格调", "Umependeza"),
    "Tu es un roi, une reine": ("Realeza pura", "Königlich", "أنت من الملوك", "Realeza pura", "你是王者", "Wewe ni mfalme"),
    "Tu déchires": ("Estás en llamas", "Du rockst", "أنت مشتعل", "Você arrasa", "你太牛了", "Unawaka moto"),
    "Génie": ("Genio", "Genie", "عبقري", "Gênio", "天才", "Mwerevu"),
    "Précieux": ("Precioso", "Kostbar", "ثمين", "Precioso", "珍贵", "Wa thamani"),
    "Sublime": ("Sublime", "Umwerfend", "رائع", "Sublime", "绝美", "Kupendeza"),
    "Parfait": ("Perfecto", "Perfekt", "ممتاز", "Perfeito", "完美", "Kamili"),
    "Respect": ("Respeto", "Respekt", "احترامي", "Respeito", "致敬", "Heshima"),
    "Cent pour cent": ("Cien por cien", "Hundert Prozent", "مئة بالمئة", "Cem por cento", "百分之百", "Asilimia mia"),
    "Quel talent": ("Qué talento", "Was für ein Talent", "يا له من موهبة", "Que talento", "真有才华", "Kipaji kikubwa"),
    # --- Amour et affection
    "Je t'aime": ("Te quiero", "Ich liebe dich", "أحبك", "Eu te amo", "我爱你", "Nakupenda"),
    "Câlin": ("Abrazo", "Umarmung", "عناق", "Abraço", "抱抱", "Kumbatio"),
    "Bisou": ("Besito", "Küsschen", "قبلة", "Beijinho", "亲亲", "Busu"),
    "Cœur qui bat": ("Corazón latiendo", "Schlagendes Herz", "قلب ينبض", "Coração batendo", "心跳", "Moyo unaodunda"),
    "Tu me manques": ("Te extraño", "Ich vermisse dich", "أشتاق إليك", "Sinto sua falta", "我想你", "Nakukumbuka"),
    "Merci du fond du cœur": ("Gracias de corazón", "Von Herzen Danke", "شكرا من كل قلبي", "Gratidão de coração", "衷心感谢", "Asante kwa moyo wote"),
    "Amis pour la vie": ("Amigos de por vida", "Freunde fürs Leben", "أصدقاء للأبد", "Amigos para sempre", "一生的朋友", "Marafiki milele"),
    "Bonne énergie": ("Buena energía", "Gute Vibes", "طاقة إيجابية", "Boas energias", "正能量", "Nishati chanya"),
    "Je pense à toi": ("Pienso en ti", "Ich denke an dich", "أفكر فيك", "Penso em você", "想你了", "Nakufikiria"),
    "Cœur brisé": ("Corazón roto", "Gebrochenes Herz", "قلب مكسور", "Coração partido", "心碎", "Moyo uliovunjika"),
    # --- Réponses rapides
    "Oui": ("Sí", "Ja", "نعم", "Sim", "是", "Ndiyo"),
    "Non": ("No", "Nein", "لا", "Não", "不", "Hapana"),
    "Peut-être": ("Quizás", "Vielleicht", "ربما", "Talvez", "也许", "Labda"),
    "D'accord": ("Vale", "Okay", "حسنا", "Beleza", "好的", "Sawa"),
    "Merci": ("Gracias", "Danke", "شكرا", "Valeu", "谢谢", "Asante"),
    "De rien": ("De nada", "Gern geschehen", "عفوا", "De nada", "不客气", "Karibu"),
    "Bonjour": ("Hola", "Hallo", "مرحبا", "Olá", "你好", "Habari"),
    "Bonne nuit": ("Buenas noches", "Gute Nacht", "تصبح على خير", "Boa noite", "晚安", "Usiku mwema"),
    "Bonsoir": ("Buenas tardes", "Guten Abend", "مساء الخير", "Boa tarde", "晚上好", "Habari za jioni"),
    "À bientôt": ("Hasta pronto", "Bis bald", "أراك قريبا", "Até logo", "回头见", "Tuonane baadaye"),
    "Un instant": ("Un momento", "Einen Moment", "لحظة من فضلك", "Um instante", "稍等", "Subiri kidogo"),
    "J'arrive": ("Ya voy", "Ich komme", "أنا قادم", "Estou chegando", "我来了", "Nakuja"),
    "Bien reçu": ("Recibido", "Erhalten", "تم الاستلام", "Recebido", "收到", "Nimepokea"),
    "Pas de souci": ("Sin problema", "Kein Problem", "لا مشكلة", "Sem problema", "没问题", "Hakuna shida"),
    "Bonne chance": ("Buena suerte", "Viel Glück", "حظا سعيدا", "Boa sorte", "祝你好运", "Bahati njema"),
    "Je croise les doigts": ("Cruzo los dedos", "Daumen drücken", "أتمنى لك التوفيق", "Dedos cruzados", "交叉手指", "Nakuombea"),
}

# Mots-clés supplémentaires (minuscules, sans accents, toutes langues). Les mots des
# légendes en alphabet latin sont ajoutés automatiquement par gen_pack.py.
KW = {
    "MDR": "mdr lol jaja haha hahaha rire rigoler mort de rire kkk 555 lmao",
    "Fou rire aux larmes": "rire larmes pleurer de rire rofl mdr lol jajaja mort de rire crying laughing",
    "Grand sourire": "sourire content heureux smile happy sonrisa feliz",
    "Youpi": "youpi yay hourra joie victoire hurra yeah yupi juhu",
    "Trop drole": "drole marrant rigolo funny lol haha gracioso lustig engracado",
    "Petit sourire": "sourire smile calme sympa ok gentil slightly",
    "Ravi": "ravi content heureux joyeux happy glad contento",
    "Danse de joie": "danse danser dance danza tanz danca ngoma fete party",
    "Hihi": "hihi hehe gloussement timide rire discret giggle jiji",
    "Rire gene": "gene embarrasse oups gene awkward sweat sueur nervioso nervoso",
    "Ca me fait plaisir": "plaisir heureux content pleased joie happy contento",
    "On fait la fete": "fete party feter celebrer confettis fiesta festa sherehe",
    "Felicitations": "felicitations bravo congrats congratulations felicidades parabens hongera fete",
    "Bravo": "bravo applaudir applaudissements clap bien joue bravo aplauso",
    "Champion": "champion coupe trophee gagnant winner victoire campeon campeao bingwa",
    "Objectif atteint": "objectif cible atteint reussi mission accomplie done goal target check valide coche",
    "Diplome": "diplome diplomee graduation ecole universite etudes bac graduado formado",
    "Nouveau travail": "travail job emploi boulot bureau work new job trabajo emprego kazi",
    "Promotion": "promotion promu carriere croissance hausse graphique up ascenso promocao",
    "Medaille d'or": "medaille or gold medal premier gagnant victoire sport",
    "Standing ovation": "ovation applaudir bravo mains levees hourra cheer",
    "Chapeau": "chapeau respect hommage bravo hat haut de forme",
    "Tu as reussi": "reussi reussite muscle force fort bravo tu peux strong flex lograste conseguiu",
    "Record battu": "record fusee rocket lancement decollage fuseee espace niveau superieur",
    "Etoile du jour": "etoile star vedette star du jour brille estrella estrela nyota",
    "On celebre": "celebrer champagne bouteille toast trinquer fete party cheers salud saude",
    "Trop beau": "beau belle magnifique jolie lovely beautiful guapo bonito coeur yeux",
    "Tu brilles": "brille etincelle brillant etoiles sparkle shine glow brillo brilho",
    "Quelle classe": "classe cool lunettes soleil elegant stylish swag sunglasses",
    "Tu es un roi, une reine": "roi reine couronne king queen royal royaute rey reina rei rainha mfalme malkia",
    "Tu deshires": "dechire feu fire flamme chaud hot lit ca chauffe fuego fogo",
    "Tu dechires": "dechire feu fire flamme chaud hot lit ca chauffe fuego fogo moto",
    "Genie": "genie intelligent cerveau brain malin smart genius inteligente",
    "Precieux": "precieux diamant gemme bijou valeur rare diamond gem tresor",
    "Sublime": "sublime superbe wow stunning etoiles yeux incroyable",
    "Parfait": "parfait ok super nickel top perfect chef kiss",
    "Respect": "respect salut militaire hommage salute honneur",
    "Cent pour cent": "cent pour cent 100 100% score parfait top total",
    "Quel talent": "talent artiste peinture art dessin creatif palette artist",
    "Je t'aime": "amour love coeur heart aime adore romantique jtm te quiero ich liebe dich eu te amo",
    "Calin": "calin hug etreinte bras reconfort abrazo umarmung abraco hugs",
    "Bisou": "bisou baiser kiss bise smack muah besito beijo busu",
    "Coeur qui bat": "coeur bat battement heartbeat pouls amour love corazon coracao moyo",
    "Tu me manques": "manque miss you triste nostalgie yeux larmoyants extrano saudade",
    "Merci du fond du coeur": "merci remerciement gratitude prier priere mains thanks thank you gracias danke obrigado asante",
    "Amis pour la vie": "amis amitie ami pote poignee de main deal friends friendship bff",
    "Bonne energie": "energie vibes arc en ciel positif rainbow good vibes paix",
    "Je pense a toi": "penser pense bulle reve thinking thought souvenir",
    "Coeur brise": "coeur brise chagrin triste peine rupture heartbreak broken sad",
    "Oui": "oui yes ok accord pouce like thumbs up daccord si sim ndiyo",
    "Non": "non no interdit refus nope negatif nein nao hapana",
    "Peut-etre": "peut etre maybe hmm reflechir doute think perhaps quiza talvez labda",
    "D'accord": "daccord ok okay entendu compris parfait vale beleza sawa",
    "Merci": "merci thanks thx thank you gracias danke obrigado valeu asante shukran",
    "De rien": "de rien avec plaisir pas de quoi welcome poignee de main karibu",
    "Bonjour": "bonjour salut coucou hello hi hey wave main hola ola salam habari jambo",
    "Bonne nuit": "nuit dormir sommeil lune night sleep good night dodo noches noite usiku",
    "Bonsoir": "soir soiree bonsoir evening crepuscule coucher de soleil ville tarde",
    "A bientot": "bientot a plus tard au revoir bye see you soon a demain coeur",
    "Un instant": "instant attends attendre sablier patience wait moment minute espera",
    "J'arrive": "arrive en route marche pieton coming otw bientot ya voy",
    "Bien recu": "recu recevoir message courrier mail enveloppe received ack recibido",
    "Pas de souci": "souci probleme no worries tranquille cool relax no problem sin problema",
    "Bonne chance": "chance trefle luck four leaf clover suerte sorte bahati",
    "Je croise les doigts": "croiser doigts espoir souhait fingers crossed hope esperar peu de chance",
}
