name: afrotok
description: "afrotok projet officiel"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
#version: 1.0.0+1
version: 1.2.4+102

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  flutter:
    sdk: flutter
  badges: ^3.1.2
  flutter_cache_manager: ^3.3.1
  collection: ^1.18.0
  numberpicker: ^2.1.2
  flutter_inner_drawer: ^1.0.0+1
  phone_form_field: ^10.0.8
  flutter_svg: ^2.0.17
  page_transition: ^2.1.0
#  ffmpeg_kit_flutter: ^4.5.1
  rxdart: ^0.27.2
  eva_icons_flutter: ^3.0.2
  image_watermark: ^0.1.0
  ionicons: ^0.1.2
  dio:
  equatable: ^2.0.3
  font_awesome_flutter: ^9.2.0
  avatar_glow: ^2.0.2
  getwidget: ^2.0.4
  fluttertagger: ^2.2.1
  tiktok_double_tap_like: ^1.0.5+2
  animated_icon: ^0.0.9
  record: ^6.1.1
#  flutter_html: ^2.2.1
  cinetpay: ^1.0.8
  flutter_widget_from_html: ^0.15.3
#  deepseek_client: ^0.0.1
  flutter_markdown: ^0.7.6+2
#  story_view: ^0.16.5
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  flutter_story_presenter: ^1.0.4
  flutter_hooks: ^0.18.1
#  hashtagable: ^2.3.0+1
  hashtagable_v3: ^3.0.1

  tap_effect: ^0.0.4
 # money_formatter:
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  anim_search_bar: ^2.0.3
  flutter_parsed_text: ^2.2.1
  video_player: ^2.8.2
  cached_network_image: ^3.2.0
  grouped_list: ^5.1.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  comment_tree: ^0.3.0
  csc_picker_plus: ^0.0.3
  country_flags: ^3.2.0
  country_code_picker: ^3.1.0
  palette_generator: ^0.3.3+6
  path_provider: ^2.0.15  # vérifie la dernière version


  #  emoji_picker_flutter: ^1.6.0
#  flutter_local_notifications: ^17.1.1
  http: any
#  flutter_share: ^2.0.0
  share_plus: ^10.1.2
  onesignal_flutter: ^5.1.2
  html: ^0.15.1
  any_link_preview: ^3.0.0
  progress_indicators: ^1.0.0
  flutter_list_view: ^1.1.22
  pull_to_refresh: ^2.0.0
  image_picker: '>=0.8.9 <2.0.0'
  audio_waveforms: ^1.0.1
  # For formatting time locale in message receipts
  timeago:
#  native_video_view: ^1.0.5
  simple_tags: ^0.0.6
  dropdown_search: ^5.0.6
  stories_for_flutter: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  loading_animation_widget: ^1.2.0+4

#  cloud_firestore: ^4.14.0
  cloud_firestore: ^5.4.3
#  firebase_storage: ^11.6.0
  firebase_storage: ^12.3.2
  firebase_dynamic_links: ^6.1.10
  flash: ^3.1.0
  pulp_flash: ^0.0.6
  searchable_listview: ^2.10.1
  popover_gtk: ^0.2.6+3
  deeplynks: ^1.0.7
  flick_video_player: ^0.9.0
  get: ^4.7.2
  webview_flutter: ^4.0.1
  tiktok_scraper: ^0.0.8
  cloud_functions: any
  app_links: ^6.4.1
  visibility_detector: ^0.4.0+2


#  image: ^2.1.4

  image: ^4.3.0
#  tflite: ^1.1.2
  camera: ^0.11.0+2
#  tflite_flutter: ^0.11.0
#  tflite_v2: ^1.0.0
  video_thumbnail: ^0.5.6
  shimmer: ^3.0.0
  rive_animated_icon: ^2.0.5
  device_info_plus: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #chatview: ^1.3.1
  intl_phone_field: ^3.2.0
  flutter_vector_icons: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  ripple_wave: ^0.1.3
  skeletonizer: ^2.1.0+1
  flutter_chat_bubble: ^2.0.2
  chat_bubbles: ^1.6.0
  audioplayers: ^5.2.1
  flutter_carousel_widget: ^3.1.0

  intl: ^0.20.0
  flutter_popup_menu_button: ^0.0.1+5
  popup_menu: ^2.0.0
  popup_menu_plus: ^0.0.6
  like_button: ^2.0.5
  chewie: ^1.7.5
  flutter_form_builder: ^10.1.0
  auto_animated: ^3.2.0
#  flutter_animated_icons: ^1.0.1
  rate_in_stars: ^0.0.3
  flutter_card_swiper: ^7.0.0
  marquee: ^2.2.3
  flutter_email_sender: ^6.0.2
  random_color: ^1.0.5
  #phone_verification: ^0.0.1
#  telephony: ^0.2.0
  introduction_screen: ^3.1.12
  awesome_dialog: ^3.2.0
  pinput: ^4.0.0
  insta_image_viewer: ^1.0.2
  restart_app: ^1.2.1
  encrypt_decrypt_plus: ^1.1.0
  preload_page_view: ^0.2.0
  google_generative_ai: ^0.4.0
  fading_edge_scrollview: ^4.1.1
  upgrader: ^11.3.1
  carousel_slider: ^5.0.0
  flutter_image_slideshow: ^0.1.6
  video_player_web_hls: ^1.3.0
  pro_image_editor: ^6.2.1
  firebase_app_check: ^0.3.1+7
#  image_gallery_saver_plus: ^3.0.5
  permission_handler: ^11.3.1
  youtube_player_flutter: ^9.1.1
  iconsax: ^0.0.8
  xml: ^6.5.0
  agora_rtc_engine: 6.5.3
  agora_rtm: ^2.2.5
  confetti: ^0.8.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  uuid: ^4.5.1







dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  json_serializable: ^6.6.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  flutter_hooks: ^0.20.5
#  flutter_svg: ^0.22.0
#  xml: ^5.0.0

#  whatsapp_camera: ^1.0.0
#  permission_handler: ^10.2.0
#  rxdart: ^0.26.0
#  camera: ^0.11.0+2
##  photofilters: ^3.0.1
##  image: ^4.3.0
#  image: ^4.3.0
#  image_cropper: ^8.1.0
#  permission_handler: ^11.3.1
#  file_picker: ^4.0.0
#  ffi: ^2.1.3








flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/afrolook_logo.png"
#  image_path: "assets/logo/afrolook_noel.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/afrolook_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/afrolook_logo.png"
#    image_path: "assets/logo/afrolook_noel.png"
    icon_size: 48 # min:48, max:256, default: 48


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icon/
     - assets/splash/
     - assets/logo/
     - assets/menu/
     - assets/icons/
     - assets/videos/
     - assets/userEticket/
     - assets/frames/
     - assets/fonts/
     - assets/fonts/file.zip

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf

      - family: NunitoBold
        fonts:
          - asset: assets/fonts/Nunito-ExtraBold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
