// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android;

    // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for windows - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBES1Ej6uR4FouRRkh-1PF1B89wRpW7bQo',
    appId: '1:186049947777:web:7dc6951123bfb3ff940580',
    messagingSenderId: '186049947777',
    projectId: 'afrolooki',
    authDomain: 'afrolooki.firebaseapp.com',
    storageBucket: 'afrolooki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vsKOoO9bPH9CKIVROA7KIyd_pq3uGiI',
    appId: '1:186049947777:android:e3723d966eb10f6c940580',
    messagingSenderId: '186049947777',
    projectId: 'afrolooki',
    storageBucket: 'afrolooki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPNN4ccgYqgwlwSqY9hTk5X-byibVVwk',
    appId: '1:186049947777:ios:a3392a8a1354d839940580',
    messagingSenderId: '186049947777',
    projectId: 'afrolooki',
    storageBucket: 'afrolooki.appspot.com',
    iosBundleId: 'com.afrotok.afrotok',
  );
}
