// Phrases de défi de la mascotte (Quiz et Étude) : culture, niveau, points (voir tr.dart).
const Map<String, Map<String, String>> kTrDefi = {
  'On ne peut pas célébrer notre culture sans la connaître. Teste ton niveau !': {'en': 'We can\'t celebrate our culture without knowing it. Test your level!', 'es': 'No podemos celebrar nuestra cultura sin conocerla. ¡Pon a prueba tu nivel!', 'de': 'Wir können unsere Kultur nicht feiern, ohne sie zu kennen. Teste dein Niveau!', 'ar': 'لا يمكننا الاحتفاء بثقافتنا دون أن نعرفها. اختبر مستواك!', 'pt': 'Não dá para celebrar a nossa cultura sem a conhecer. Teste o seu nível!', 'zh': '不了解我们的文化，就无法庆祝它。来测测你的水平吧！', 'sw': 'Hatuwezi kusherehekea utamaduni wetu bila kuujua. Jaribu kiwango chako!'},
  'Tu te crois capable de répondre à 3 questions sans faute ?': {'en': 'Think you can answer 3 questions without a single mistake?', 'es': '¿Crees que puedes responder 3 preguntas sin ningún error?', 'de': 'Glaubst du, du schaffst 3 Fragen ohne einen Fehler?', 'ar': 'هل تظن أنك تستطيع الإجابة عن 3 أسئلة دون أي خطأ؟', 'pt': 'Acha que consegue responder a 3 perguntas sem nenhum erro?', 'zh': '你觉得自己能 3 道题全对吗？', 'sw': 'Unadhani unaweza kujibu maswali 3 bila kosa lolote?'},
  'Teste ton niveau d\'intello ici !': {'en': 'Test your brainiac level here!', 'es': '¡Pon a prueba tu nivel de cerebrito aquí!', 'de': 'Teste hier dein Streber-Niveau!', 'ar': 'اختبر مستوى ذكائك هنا!', 'pt': 'Teste aqui o seu nível de intelectual!', 'zh': '在这里测测你的学霸水平！', 'sw': 'Jaribu kiwango chako cha akili hapa!'},
  'Gagne des points avec ta connaissance !': {'en': 'Earn points with your knowledge!', 'es': '¡Gana puntos con tus conocimientos!', 'de': 'Sammle Punkte mit deinem Wissen!', 'ar': 'اكسب النقاط بمعرفتك!', 'pt': 'Ganhe pontos com o seu conhecimento!', 'zh': '用你的知识赢取积分！', 'sw': 'Pata pointi kwa maarifa yako!'},
  'Trois questions, zéro erreur : prouve-le !': {'en': 'Three questions, zero mistakes: prove it!', 'es': 'Tres preguntas, cero errores: ¡demuéstralo!', 'de': 'Drei Fragen, null Fehler: beweise es!', 'ar': 'ثلاثة أسئلة وبلا أخطاء: أثبت ذلك!', 'pt': 'Três perguntas, zero erros: prove!', 'zh': '三道题，零失误：证明给大家看！', 'sw': 'Maswali matatu, makosa sifuri: thibitisha!'},
  'Tes amis savent beaucoup… et toi ? Grimpe au classement !': {'en': 'Your friends know a lot… and you? Climb the ranking!', 'es': 'Tus amigos saben mucho… ¿y tú? ¡Sube en la clasificación!', 'de': 'Deine Freunde wissen viel … und du? Klettere in der Rangliste!', 'ar': 'أصدقاؤك يعرفون الكثير… وأنت؟ اصعد في الترتيب!', 'pt': 'Os seus amigos sabem muito… e você? Suba no ranking!', 'zh': '你的朋友知道很多……你呢？爬上排行榜吧！', 'sw': 'Marafiki zako wanajua mengi… na wewe? Panda kwenye orodha ya viwango!'},
  'Connaître l\'Afrique, c\'est la faire briller. À toi de jouer !': {'en': 'Knowing Africa is making it shine. Your turn to play!', 'es': 'Conocer África es hacerla brillar. ¡Te toca jugar!', 'de': 'Afrika zu kennen heißt, es zum Leuchten zu bringen. Du bist dran!', 'ar': 'معرفة إفريقيا تعني جعلها تتألق. حان دورك!', 'pt': 'Conhecer a África é fazê-la brilhar. É a sua vez!', 'zh': '了解非洲，就是让它闪耀。轮到你了！', 'sw': 'Kuijua Afrika ni kuifanya iangaze. Zamu yako!'},
  'Un cerveau bien rempli vaut de l\'or : fais le plein de points !': {'en': 'A well-filled brain is worth gold: stock up on points!', 'es': 'Un cerebro bien lleno vale oro: ¡llénate de puntos!', 'de': 'Ein gut gefülltes Gehirn ist Gold wert: sammle Punkte!', 'ar': 'العقل الغني كنز: املأ رصيدك بالنقاط!', 'pt': 'Um cérebro bem cheio vale ouro: encha-se de pontos!', 'zh': '充实的大脑价值千金：多拿点积分吧！', 'sw': 'Akili iliyojaa ina thamani ya dhahabu: jipatie pointi nyingi!'},
  'Savoir, c\'est pouvoir : lis ce cours et teste-toi !': {'en': 'Knowledge is power: read this course and test yourself!', 'es': 'Saber es poder: ¡lee este curso y ponte a prueba!', 'de': 'Wissen ist Macht: lies diesen Kurs und teste dich!', 'ar': 'المعرفة قوة: اقرأ هذا الدرس واختبر نفسك!', 'pt': 'Saber é poder: leia este curso e teste-se!', 'zh': '知识就是力量：读读这门课，再测测自己！', 'sw': 'Maarifa ni nguvu: soma somo hili kisha ujipime!'},
  'Tu crois tout savoir ? Lis ce cours, puis prouve-le au quiz !': {'en': 'Think you know it all? Read this course, then prove it in the quiz!', 'es': '¿Crees que lo sabes todo? Lee este curso y demuéstralo en el quiz.', 'de': 'Du glaubst, alles zu wissen? Lies diesen Kurs und beweise es im Quiz!', 'ar': 'هل تظن أنك تعرف كل شيء؟ اقرأ الدرس ثم أثبت ذلك في الاختبار!', 'pt': 'Acha que sabe tudo? Leia este curso e prove no quiz!', 'zh': '自以为什么都懂？先读这门课，再用测验证明！', 'sw': 'Unadhani unajua kila kitu? Soma somo hili kisha thibitisha kwenye jaribio!'},
  'Un cours lu, un quiz réussi : gagne tes points de savoir !': {'en': 'One course read, one quiz passed: earn your knowledge points!', 'es': 'Un curso leído, un quiz superado: ¡gana tus puntos de saber!', 'de': 'Ein Kurs gelesen, ein Quiz bestanden: sammle deine Wissenspunkte!', 'ar': 'درس مقروء واختبار ناجح: اكسب نقاط المعرفة!', 'pt': 'Um curso lido, um quiz vencido: ganhe os seus pontos de saber!', 'zh': '读完一门课，通过一次测验：赢取你的知识积分！', 'sw': 'Somo moja, jaribio moja: pata pointi zako za maarifa!'},
  'Ton diplôme se gagne avec ta tête : montre ce que tu vaux !': {'en': 'Your diploma is earned with your brain: show what you\'re worth!', 'es': 'Tu diploma se gana con la cabeza: ¡demuestra lo que vales!', 'de': 'Dein Diplom verdienst du mit dem Kopf: zeig, was du kannst!', 'ar': 'شهادتك تُكتسب بعقلك: أظهر قيمتك!', 'pt': 'O seu diploma ganha-se com a cabeça: mostre o que vale!', 'zh': '文凭靠头脑赢得：展示你的实力吧！', 'sw': 'Cheti chako kinapatikana kwa akili: onyesha thamani yako!'},
};
