// Traductions du widget « Rejoins-nous sur nos autres réseaux » (voir tr.dart).
const Map<String, Map<String, String>> kTrSocial = {
  'Cela peut prendre un peu de temps': {'en': 'This may take a little while', 'es': 'Puede tardar un poco', 'de': 'Das kann einen Moment dauern', 'ar': 'قد يستغرق ذلك بعض الوقت', 'pt': 'Pode levar um pouco de tempo', 'zh': '这可能需要一点时间', 'sw': 'Hii inaweza kuchukua muda kidogo'},
  'Facebook : prise en compte en cours…': {'en': 'Facebook: being processed…', 'es': 'Facebook: en proceso…', 'de': 'Facebook: wird verarbeitet…', 'ar': 'فيسبوك: قيد المعالجة…', 'pt': 'Facebook: em processamento…', 'zh': 'Facebook：处理中…', 'sw': 'Facebook: inashughulikiwa…'},
  'TikTok : prise en compte en cours…': {'en': 'TikTok: being processed…', 'es': 'TikTok: en proceso…', 'de': 'TikTok: wird verarbeitet…', 'ar': 'تيك توك: قيد المعالجة…', 'pt': 'TikTok: em processamento…', 'zh': 'TikTok：处理中…', 'sw': 'TikTok: inashughulikiwa…'},
  'Merci pour ton soutien 💚': {'en': 'Thanks for your support 💚', 'es': 'Gracias por tu apoyo 💚', 'de': 'Danke für deine Unterstützung 💚', 'ar': 'شكرًا على دعمك 💚', 'pt': 'Obrigado pelo seu apoio 💚', 'zh': '感谢你的支持 💚', 'sw': 'Asante kwa msaada wako 💚'},
  '12 K abonnés sur Facebook': {'en': '12K followers on Facebook', 'es': '12 K seguidores en Facebook', 'de': '12 Tsd. Follower auf Facebook', 'ar': '12 ألف متابع على فيسبوك', 'pt': '12 mil seguidores no Facebook', 'zh': 'Facebook 上有 1.2 万粉丝', 'sw': 'Wafuasi 12K kwenye Facebook'},
  'Rejoins-nous sur nos autres réseaux': {'en': 'Join us on our other networks', 'es': 'Únete a nosotros en nuestras otras redes', 'de': 'Begleite uns in unseren anderen Netzwerken', 'ar': 'انضم إلينا على شبكاتنا الأخرى', 'pt': 'Junte-se a nós nas outras redes', 'zh': '在我们的其他平台加入我们', 'sw': 'Jiunge nasi kwenye mitandao yetu mingine'},
  'Suis, partage et commente nos publications. Plus la communauté Afrolook grandit, plus tes gains peuvent augmenter.': {'en': 'Follow, share and comment on our posts. The more the Afrolook community grows, the more your earnings can grow.', 'es': 'Sigue, comparte y comenta nuestras publicaciones. Cuanto más crece la comunidad Afrolook, más pueden aumentar tus ganancias.', 'de': 'Folge, teile und kommentiere unsere Beiträge. Je mehr die Afrolook-Community wächst, desto mehr können deine Einnahmen steigen.', 'ar': 'تابع منشوراتنا وشاركها وعلّق عليها. كلما كبر مجتمع Afrolook زادت أرباحك.', 'pt': 'Siga, compartilhe e comente nossas publicações. Quanto mais a comunidade Afrolook cresce, mais seus ganhos podem aumentar.', 'zh': '关注、分享并评论我们的帖子。Afrolook 社区越壮大，你的收益就可能越多。', 'sw': 'Fuata, shiriki na toa maoni kwenye machapisho yetu. Jumuiya ya Afrolook inavyokua, ndivyo mapato yako yanavyoweza kuongezeka.'},
  'Retrouve Afrolook ailleurs': {'en': 'Find Afrolook elsewhere', 'es': 'Encuentra Afrolook en otros sitios', 'de': 'Finde Afrolook auch anderswo', 'ar': 'اعثر على Afrolook في أماكن أخرى', 'pt': 'Encontre o Afrolook em outros lugares', 'zh': '在其他平台找到 Afrolook', 'sw': 'Pata Afrolook kwingineko'},
};
